name: Trigger E2E Tests

on:
  workflow_call:

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: e2e-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-matrix-android:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    env:
      ANDROID_EMULATOR_API_LEVEL: 28
      ANDROID_EMULATOR_TARGET: default
      ANDROID_EMULATOR_ARCH: x86_64
      ANDROID_EMULATOR_DISK_SPACE: 1024M
      ANDROID_EMULATOR_RAM_SIZE: 256M
      ANDROID_EMULATOR_HEAP_SIZE: 256M
      ANDROID_EMULATOR_BOOT_TIMEOUT: 2700
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Determine whether metro apps are affected
        id: check-ci
        run: |
          if node tools/scripts/ci-is-affected.mjs --appName=${{ matrix.app_name }}; then
            echo "run-e2e=true" >> "$GITHUB_OUTPUT"
          else
            echo "run-e2e=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Android E2E Tests
        if: steps.check-ci.outputs.run-e2e == 'true'
        uses: ./.github/actions/android-e2e
        with:
          app_name: ${{ matrix.app_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
  e2e-matrix-ios:
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    env:
      RUBY_VERSION: 2.7.6
      MAESTRO_VERSION: 1.39.13
      MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js 20
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Determine whether metro apps are affected
        id: check-ci
        run: |
          if node tools/scripts/ci-is-affected.mjs --appName=${{ matrix.app_name }}; then
            echo "run-e2e=true" >> "$GITHUB_OUTPUT"
          else
            echo "run-e2e=false" >> "$GITHUB_OUTPUT"
          fi

      - name: iOS E2E Tests
        if: steps.check-ci.outputs.run-e2e == 'true'
        uses: ./.github/actions/ios-e2e
        with:
          app_name: ${{ matrix.app_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
