name: Trigger E2E Tests

on:
  workflow_call:

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write

jobs:
  e2e-matrix-android:
    concurrency:
      group: e2e-tests-android-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.app_name }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    env:
      ANDROID_EMULATOR_API_LEVEL: 28
      ANDROID_EMULATOR_TARGET: default
      ANDROID_EMULATOR_ARCH: x86_64
      ANDROID_EMULATOR_DISK_SPACE: 1024M
      ANDROID_EMULATOR_RAM_SIZE: 256M
      ANDROID_EMULATOR_HEAP_SIZE: 256M
      ANDROID_EMULATOR_BOOT_TIMEOUT: 2700
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Android E2E Tests
        uses: ./.github/actions/android-e2e
        with:
          app_name: ${{ matrix.app_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  e2e-matrix-ios:
    concurrency:
      group: e2e-tests-ios-${{ github.run_id }}-${{ github.run_attempt }}-${{ matrix.app_name }}
      cancel-in-progress: true
    runs-on: macos-latest
    timeout-minutes: 60
    strategy:
      matrix:
        app_name: [example-host]
    env:
      RUBY_VERSION: 2.7.6
      MAESTRO_VERSION: 1.39.13
      MAESTRO_DRIVER_STARTUP_TIMEOUT: 360000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: iOS E2E Tests
        uses: ./.github/actions/ios-e2e
        with:
          app_name: ${{ matrix.app_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
