# .github/workflows/e2e-next-dev.yml
name: E2E Test for Next.js Dev

on:
  workflow_call:

jobs:
  e2e-next:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Pnpm
        run: corepack enable

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Set Nx SHA
        uses: nrwl/nx-set-shas@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Run condition check script
        id: check-ci
        run: node tools/scripts/ci-is-affected.mjs --appName=3000-home

      - name: E2E Test for Next.js Prod
        if: steps.check-ci.outcome == 'success'
        run: |
          pnpm run --filter @module-federation/3002-checkout --filter @module-federation/3000-home --filter @module-federation/3001-shop build &&
          pnpm run app:next:prod &
          sleep 2 &&
          npx wait-on tcp:3001 &&
          npx wait-on tcp:3002 &&
          npx wait-on tcp:3000 &&
          npx nx run-many --target=test:e2e --projects=3000-home,3001-shop,3002-checkout --parallel=3 &&
          lsof -ti tcp:3000,3001,3002 | xargs kill

      - name: E2E Test for Next.js Dev
        if: steps.check-ci.outcome == 'success'
        run: |
          pnpm run app:next:dev > /dev/null 2>&1 &
          sleep 1 &&
          npx wait-on tcp:3001 &&
          npx wait-on tcp:3002 &&
          npx wait-on tcp:3000 &&
          npx nx run-many --target=test:e2e --projects=3000-home,3001-shop,3002-checkout --parallel=1 &&
          lsof -ti tcp:3000,3001,3002 | xargs kill
