name: deploy-website

on: 
  push:

# on:
#   pull_request:
#   push:
#     branches:
#       - main

env:
  BASE_REF: ${{ github.event_name == 'pull_request' && format('remotes/origin/{0}', github.base_ref) || 'HEAD~1' }}
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Pre-determine if website app is affected
      website-changed: ${{ steps.website-changed.outputs.website-changed }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: github.event_name == 'pull_request'
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Check changes "website"
        id: website-changed
        run: echo "website-changed=$(node tools/scripts/ci-is-affected.mjs --appName=website --base=${{ env.BASE_REF}} --head=HEAD)" >> $GITHUB_OUTPUT
      - name: Log variables
        run: |
          echo "steps.cache.outputs.cache-hit:" ${{ steps.cache.outputs.cache-hit }}
          echo "steps.website-changed.outputs.website-changed:" ${{ steps.website-changed.outputs.website-changed }}

  deploy-website:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    needs: setup
    # if: ${{ needs.setup.outputs.website-changed == 'true' && github.event_name == 'push' }}
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn.lock') }}
      - run: npm run build:website
      - run: "npm install -g netlify-cli && npx netlify deploy --build --prod --message \"Deploy from GitHub Actions\""
        
          
  # preview-website:
  #   name: 'Deploy Netlify Preview'
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   if: ${{ needs.setup.outputs.website-changed == 'true' && github.event_name == 'pull_request' }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: ${{ env.CACHE_NODE_MODULES_PATH }}
  #         key: build-${{ hashFiles('**/yarn.lock') }}
  #     - run: npm run build:website
  #     # Sets the branch name as environment variable
  #     - uses: nelonoel/branch-name@v1.0.1
  #     - uses: nwtgck/actions-netlify@v2.0.0
  #       id: publish-preview
  #       with:
  #         publish-dir: ./dist/apps/website/client
  #         deploy-message: "Deploy Preview from GitHub Actions"
  #         production-deploy: false
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         alias: ${{ env.BRANCH_NAME }}
  #       env:
  #         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  #         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  #       timeout-minutes: 1