name: deploy-website

on:
  pull_request:
  push:
    branches:
      - main

env:
  BASE_REF: ${{ github.event_name == 'pull_request' && format('remotes/origin/{0}', github.base_ref) || 'HEAD~1' }}
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Pre-determine if website app is affected
      website-changed: ${{ steps.website-changed.outputs.website-changed }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        if: github.event_name == 'pull_request'
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Check changes "website"
        id: website-changed
        run: echo "website-changed=$(node tools/scripts/ci-is-affected.mjs --appName=website --base=${{ env.BASE_REF}} --head=HEAD)" >> $GITHUB_OUTPUT
      - name: Log variables
        run: |
          echo "steps.cache.outputs.cache-hit:" ${{ steps.cache.outputs.cache-hit }}
          echo "steps.website-changed.outputs.website-changed:" ${{ steps.website-changed.outputs.website-changed }}

  deploy-website:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.website-changed == 'true' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn.lock') }}
      - run: npm run build:website
      - run: "npx netlify deploy --build --prod --message \"Deploy from GitHub Actions\""
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_NEXT_PLUGIN_SKIP: true

  preview-website:
    name: 'Deploy Netlify Preview'
    runs-on: ubuntu-latest
    needs: setup
    # if: ${{ needs.setup.outputs.website-changed == 'true' && github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn.lock') }}
      - uses: nelonoel/branch-name@v1.0.1
      - run: npm run build:website
      - uses: South-Paw/action-netlify-cli@1.0.1
        id: netlify
        with: "'deploy --build --message \"Deploy Preview from GitHub Actions\" --alias \"${{ env.BRANCH_NAME }}\"'"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_NEXT_PLUGIN_SKIP: true

      # Handle PR commenting
      - name: Find Relevant Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          token: ${{ inputs.github_token }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Deploy Preview is ready'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ inputs.github_token }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## âœ… Deploy Preview is ready!
            | Name          | Link          |
            | ------------- | ------------- |
            | ðŸ”¨ Latest commit  | ${{ github.sha }}            |
            | ðŸ˜Ž Deploy Preview | ${{ steps.netlify.outputs.NETLIFY_DRAFT_URL }}  |
          edit-mode: replace