name: deploy-docs

on:
  push:
    branches:
      - main

env:
  BASE_REF: ${{ 'HEAD~1' }}
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      # Pre-determine if docs app is affected
      docs-changed: ${{ steps.docs-changed.outputs.docs-changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Check changes "docs"
        id: docs-changed
        run: echo "docs-changed=$(node tools/scripts/ci-is-affected.mjs --appName=docs --base=${{ env.BASE_REF}} --head=HEAD)" >> $GITHUB_OUTPUT
      - name: Log variables
        run: |
          echo "steps.cache.outputs.cache-hit:" ${{ steps.cache.outputs.cache-hit }}
          echo "steps.docs-changed.outputs.docs-changed:" ${{ steps.docs-changed.outputs.docs-changed }}

  deploy-docs:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.outputs.docs-changed == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/yarn-lock.json') }}
      - run: npx nx run docs:build-docs
      - uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ./dist/apps/docs
          deploy-message: "Deploy from GitHub Actions"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

