name: PR-Workflow

on: pull_request

env:
  CACHE_NODE_MODULES_PATH: |
    ~/.npm
    node_modules

jobs:
  build_checks:
    name: Build Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - run: git fetch --no-tags --prune --depth=5 origin main
        name: Fetch Main branch
      - uses: actions/cache@v3
        id: cache
        with:
          path: ${{ env.CACHE_NODE_MODULES_PATH }}
          key: build-${{ hashFiles('**/package-lock.json') }}
      - name: Install packages
        run: npm i
      - name: Retrieve effected projects
        id: effected-projects
        run: echo "projects=$($(yarn bin)/nx print-affected --type=lib --select=projects --base=origin/main)" >> $GITHUB_OUTPUT
      - name: Lint
        shell: bash
        run: |
          if [[ "${{ steps.effected-projects.outputs.projects }}" ]]; then
            yarn nx run-many --target=lint --projects="$PROJECTS" --maxParallel=10
          else
            echo "No changes, Skipping lint check."
          fi
      - name: Test
        shell: bash
        run: |
          if [[ "${{ steps.effected-projects.outputs.projects }}" ]]; then
            yarn nx run-many --target=test --projects="$PROJECTS" --maxParallel=10
          else
            echo "No changes, Skipping tests."
          fi
      - name: Build
        shell: bash
        run: |
          if [[ "${{ steps.effected-projects.outputs.projects }}" ]]; then
            yarn nx run-many --target=build --projects="$PROJECTS" --maxParallel=10
          else
            echo "No changes, Skipping build."
          fi
