antora:
  extensions:
    - require: antora-navigator-extension
      config_file: ./mf-antora-navigator.yml
    - require: '@antora/lunr-extension'
      languages: [en, es, zh]
site:
  title: 模块联合文档
  start_page: ROOT:getting-started.adoc
  keys:
    google_analytics: G-SDV5HRTM4G
urls:
  html_extension_style: indexify
content:
  sources:
    - url: ./../../../
      start_path: apps/docs/src/zh_CN
      edit_url: '{web_url}/blob/{refname}/{path}'
ui:
  bundle:
    url: ./../../../apps/docs-ui/dist
    snapshot: false
  # supplemental_files: ./../../../node_modules/antora-navigator-extension/data/
output:
  clean: true
  dir: ./../../../dist/apps/docs/zh
runtime:
  fetch: true
  cache_dir: ./../../../tmp/docs-cache/zh
asciidoc:
  extensions:
    - '@asciidoctor/tabs'
  attributes:
    page-pagination: yes
    language: zh
